### ISSUE TITLE
OBS Streaming

### ISSUE THREAD

**Issue by rayj00** [livepeer/wiki#26]
For the steps of running OBS, clarify that the "localhost" is the IP address of the newly created node previously created .  

Other than that, nice job!

**Comment by chrishobcroft** [comment]
I'm not sure I understand.

Inputting `rtmp://localhost:1935` works for OBS to find the server.

Are you suggesting to replace localhost with e.g. `192.168.0.131`

Or are you just suggesting that I explain what `localhost` means?
